In [28]:
import numpy as np
import string
from collections import Counter
#opening the text file in read mode
text = open('speeches.txt', 'r')
#convert the file to single string
s = text.read()

In [37]:
#list all the to be excluded characters from the text given
#make the listing as a string
exclude = set(string.punctuation)
#our string extracted from the text is now modified
#modification is removing all punctuations listed above
s_modified = ''.join(ch for ch in s if ch not in exclude)
#lowercasing the string
s_modified=s_modified.lower()
#further modification to string by keeping only alphabets in it
#method to get rid of numbers
#appyling a technique to achieve that
#technique: if the character is alphabet, put the same character in the string
#if the character is not an alphabet, put a string space instead of the character
#getting a new string by using this technique
new_s = ''
for ch in s_modified:
    if(ch.isalpha()):
        new_s+=ch
    else:
        new_s+=' '
#splitting the string to words based on spaces
words = new_s.split()
#NOTE: It is your choice to remove the most common words
#Here it is not done, but your choice!
counter=Counter(words)
print("MOST COMMON WORD[S]:",counter.most_common(10))
print(len(words))
print(words)

MOST COMMON WORD[S]: [('the', 9776), ('to', 4558), ('a', 4422), ('and', 4392), ('of', 3781), ('in', 3491), ('for', 1822), ('that', 1794), ('is', 1410), ('on', 1319)]
168240
['valid', 'only', 'at', 'participating', 'locations', 'while', 'supplies', 'last', 'batteries', 'not', 'included', 'objects', 'in', 'mirror', 'may', 'be', 'closer', 'than', 'they', 'appear', 'other', 'necessary', 'disclaimers', 'inspired', 'by', 'mark', 'obmasciks', 'nonfiction', 'book', 'david', 'frankels', 'film', 'observes', 'the', 'migratory', 'patterns', 'of', 'three', 'breeds', 'of', 'birders', 'do', 'they', 'crisscross', 'the', 'country', 'from', 'alaskas', 'aleutians', 'to', 'floridas', 'everglades', 'because', 'they', 'feel', 'trapped', 'by', 'their', 'lives', 'or', 'because', 'by', 'observing', 'avian', 'life', 'they', 'better', 'understand', 'humans', 'yes', 'and', 'maybe', 'suggests', 'this', 'gently', 'eccentric', 'film', 'from', 'frankel', 'the', 'devil', 'wears', 'prada', 'marley', 'me', 'parker', 'fr

In [42]:
words_unique = []
for word in words:
    if word not in words_unique:
        words_unique.append(word)

print(len(words_unique))
print(words_unique)

20930
['valid', 'only', 'at', 'participating', 'locations', 'while', 'supplies', 'last', 'batteries', 'not', 'included', 'objects', 'in', 'mirror', 'may', 'be', 'closer', 'than', 'they', 'appear', 'other', 'necessary', 'disclaimers', 'inspired', 'by', 'mark', 'obmasciks', 'nonfiction', 'book', 'david', 'frankels', 'film', 'observes', 'the', 'migratory', 'patterns', 'of', 'three', 'breeds', 'birders', 'do', 'crisscross', 'country', 'from', 'alaskas', 'aleutians', 'to', 'floridas', 'everglades', 'because', 'feel', 'trapped', 'their', 'lives', 'or', 'observing', 'avian', 'life', 'better', 'understand', 'humans', 'yes', 'and', 'maybe', 'suggests', 'this', 'gently', 'eccentric', 'frankel', 'devil', 'wears', 'prada', 'marley', 'me', 'parker', 'frames', 'her', 'tale', 'as', 'a', 'love', 'story', 'between', 'greataunt', 'mary', 'husband', 'thomas', 'henry', 'davison', 'she', 'spices', 'with', 'an', 'intriguing', 'family', 'heirloom', 'skirt', 'wore', 'climbed', 'into', 'lifeboat', 'that', 'too

In [44]:
A = np.zeros((20930, 20930))
for i in range(168239):
    index_i=words_unique.index(words[i])
    index_j=words_unique.index(words[i+1])
    A[index_i][index_j]+=1
print(A)
#NOTE: As the matrix is too big, numpy shows only some part of it
#very bad indeed!

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [52]:
#taking input the first word of the funny text
vocabulary = str(input())
#function to generate words of funny text 
def funny_text_generator(vocabulary):
    #finding the index of current word
    index = words_unique.index(vocabulary)
    #creating two lists, 
    #freq list=frequencies of context words given current word
    #cumm_prob list=cummulative probabilities of context words given current word
    freq=np.zeros(len(words_unique))
    cumm_prob = np.zeros(len(words_unique))
    #finding total sum of frequency list
    tot_freq=sum(A[index])
    #converting the frequency list to probability list
    #as the frequency list is conditional(i.e. frequency of occurence of context word
    #       given current word) so the new frequency list gets converted to conditional
    #       probability list
    #by applying simple bayes rule we can extract the highest probable words
    for i in range(len(words_unique)):
        freq[i]=(A[index][i]/tot_freq)
    #creating cumm_prob list
    sot=0
    for i in range(len(words_unique)):
        sot = sot+freq[i]
        cumm_prob[i]=sot
    #if we always choose the highest probable words given current word, 
    #   then the word which comes after the current word is fixed
    #   upon each occurence of current word
    #So we toss a coin and choose the word accordingly
    #tossing a coin to choose the next word RANDOMLY!
    #by doing this we give a chance to all probabilities
    #less probable words get less chance of picking 
    #more probable words get more chance of picking
    coin = np.random.rand()
    for i in range(len(words_unique)):
        if(coin<=cumm_prob[i]):
            #appending the picked word to funny_text list
            funny_text.append(words_unique[i])
            break
    return words_unique[i]
#calling functions
funny_text = []
funny_text.append(vocabulary)
#taking input size of the funny text to be generated
n=int(input())
for i in range(n):
    vocabulary=funny_text_generator(vocabulary)
funny_str=''
for word in funny_text:
    funny_str+=word
    funny_str+=' '
#printing the funny text
print(funny_str)

#NOTE: It is funny because if you go through the words, you feel that it makes some sense
#    but as a whole it is just a bunch of nonsense!
#    it will mostly be grammatically correct though 

valid
1000
valid only of her new england in september and dismissed bloombergs report came across from catalan that should i try a person with regards to save money to organize exchanging vows i just another batch and catcher surrounded by now in the indignity or avoid the report issued by screeners that specializes in north america grand jury convicted of rome and it become more than percent peter and its players weve done in chicago has not playing well if you dont have won to not be clad in cash rewards of two weeks prices can hear from mbps tell whether the beating in a part of the bill shoemakers first earth mobs of her personal involvement in newer dish and lowincome residents if the recession has shown leadership had a host of us speak with bated breath of a surfaced soon as ceo pay for her husband david samson said byrd was barking inside apartment in a healthy sleep per serving a breast stuffed with industrial applications and are still identify that his report was trying to o